version: "2.1"
services:
  spark-master:
    image: feathub-spark:latest
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
    depends_on:
      - datanode
    command:
      - bash
      - -c
      - "./sbin/start-master.sh; while true; do sleep 10; done"

  spark-worker:
    image: feathub-spark:latest
    container_name: spark-worker
    ports:
      - "8081:8080"
      - "7000:7000"
    depends_on:
      - spark-master
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=500M
    volumes:
       - ./main.py:/tmp/main.py
    command:
      - bash
      - -c
      - "./sbin/start-worker.sh spark://spark-master:7077; while true; do sleep 10; done"

  namenode:
    image: bde2020/hadoop-namenode:1.1.0-hadoop2.7.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HDFS_CONF_dfs_permissions_enabled=false
    ports:
      - "8020:8020"
      - "50070:50070"

  datanode:
    image: bde2020/hadoop-datanode:1.1.0-hadoop2.7.1-java8
    container_name: datanode
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020
      - HDFS_CONF_dfs_permissions_enabled=false
    depends_on:
      - namenode
    ports:
      - "50075:50075"
    volumes:
      - ./data:/tmp/spark-data
